aws_region             = "us-east-1"
upload_bucket_name     = "devops-accelerator-upload-bucket"
frontend_bucket_name   = "devops-accelerator-frontend-hosting-bucket"
cloudfront_price_class = "PriceClass_100"
notification_email     = "vinitranjan74@gmail.com"
